### ISSUE TITLE
invalid conversion 

### ISSUE THREAD

**Issue by mateituca** [openhomeautomation/home-automation-arduino#1]
Arduino: 1.6.4 (Windows 8.1), Board: "Arduino Uno"

sketch_jul12a:13: error: invalid conversion from 'int' to 't_backlighPol' [-fpermissive]
In file included from sketch_jul12a.ino:5:0:
C:\Program Files (x86)\Arduino\libraries\fmalpartida-new-liquidcrystal-ba76a8c1f175/LiquidCrystal_I2C.h:53:4: error:   initializing argument 3 of 'LiquidCrystal_I2C::LiquidCrystal_I2C(uint8_t, uint8_t, t_backlighPol)' [-fpermissive]
    LiquidCrystal_I2C (uint8_t lcd_Addr, uint8_t backlighPin, t_backlighPol pol);
    ^
C:\Program Files (x86)\Arduino\libraries\fmalpartida-new-liquidcrystal-ba76a8c1f175/LiquidCrystal_I2C.h: In function 'void setup()':
C:\Program Files (x86)\Arduino\libraries\fmalpartida-new-liquidcrystal-ba76a8c1f175/LiquidCrystal_I2C.h:154:9: error: 'int LiquidCrystal_I2C::init()' is private
    int  init();
         ^
sketch_jul12a:21: error: within this context
invalid conversion from 'int' to 't_backlighPol' [-fpermissive]

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by marcoschwartz** [comment]
Hello,

Can you tell me which chapter of the book or sketch you are trying to compile exactly ? Thanks!

**Comment by mateituca** [comment]
Hello,

I was trying to do the LCD plus sensors. The part that didn't work was the
one connecting the Lcd. I think the code is not ok. I searched the Internet
and other forums and I eventually succeeded...

Best regards
Matei

**Comment by marcoschwartz** [comment]
Great, marking this as closed :) Can you tell me what you did to fix it so I can modify the code & the book accordingly? Thanks!
